### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by jlelse** [afollestad/async#1]
Is it possible to specify a delay or something like that? Or maybe something like pausing the action for some seconds?

**Comment by afollestad** [comment]
Pausing wouldn't be too practical, because it would be completely dependent on user implementation.

Do you mean delay before an action is executing? On the individual level or pool level?

**Comment by jlelse** [comment]
Delay before execution is a good idea too. But this is possible through using a handler right?

**Comment by afollestad** [comment]
Well, all that action execution is, is executing the `run()` method from a background thread:

https://github.com/afollestad/async/blob/master/library/src/main/java/com/afollestad/async/Action.java#L58

**Comment by jlelse** [comment]
So I can use Thread.sleep?

**Comment by afollestad** [comment]
Of course, that's used a few times in the sample project, I believe. No need to catch the exception for `sleep()` either, since the `run()` method does that for you.
